###################################################################################################
# oc process -f ./mdl-issuer-fe.yaml --param-file ./mdl-issuer-fe.dev.params  | oc apply -f -
###################################################################################################
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: ${APP_NAME}
  annotations:
    description: Application frontend pour l'expérimentation d'intégration du standard (ISO 18013-5) "Mobile driver's license" ou "mDl" aux attestations vérifiables.
    tags: CQEN, ING, Hyperledger, ARIES, Indy, ISO 18013-5 (mDL), PostgreSql
objects:
- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: ${APP_NAME}
  data:
    environment.js: |
      // set some defaults here
      window.FAVOURITE_SONG = "The Locomotion"
      window.FAVOURITE_ERA = "Mid-90s Nick Cave Kylie"
- kind: BuildConfig
  apiVersion: build.openshift.io/v1  
  metadata:
    labels:
      app: ${APP_NAME}
      app.kubernetes.io/component: react-app
      app.kubernetes.io/instance: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${APP_NAME}:latest
    source:
      contextDir: ${CONTEXT_DIR}
      git:
        uri: ${SOURCE_REPOSITORY_URL}
        ref: ${SOURCE_REPOSITORY_REF}
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: nginx:latest
        env:
          - name: REACT_APP_ISSUER_API_BASE_URL
            valueFrom:
              secretKeyRef:
                name: ${APP_NAME}
                key: REACT_APP_ISSUER_API_BASE_URL
          - name: REACT_APP_OID4VCI_SUPPORTED_CREDENTIAL_ID
            valueFrom:
              secretKeyRef:
                name: ${APP_NAME}
                key: REACT_APP_OID4VCI_SUPPORTED_CREDENTIAL_ID
      type: Docker
    triggers:
    - type: ConfigChange
    - type: ImageChange
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    labels:
      app: ${APP_NAME}
      app.kubernetes.io/component: react-app
      app.kubernetes.io/instance: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    strategy:
      type: Recreate
    replicas: 1
    selector:
      deploymentconfig: ${APP_NAME}
    template:
      metadata:
        labels:
          deploymentconfig: ${APP_NAME}
      spec:
        containers:
        - image: ${APP_NAME}
          imagePullPolicy: Always
          name: react-app
          env:
            - name: WEBHOOK_URL
              value: ${WEBHOOK_URL}
            - name: REACT_APP_ISSUER_API_BASE_URL
              valueFrom:
                  secretKeyRef:
                    name: ${APP_NAME}
                    key: REACT_APP_ISSUER_API_BASE_URL
            - name: REACT_APP_OID4VCI_SUPPORTED_CREDENTIAL_ID
              valueFrom:
                  secretKeyRef:
                    name: ${APP_NAME}
                    key: REACT_APP_OID4VCI_SUPPORTED_CREDENTIAL_ID
          ports:
          - containerPort: 8080
            protocol: TCP
          volumeMounts:
            - name: app-config-volume
              mountPath: /app/environment.js
              subPath: environment.js
        volumes:
          - name: app-config-volume
            configMap:
              name: ${APP_NAME}
    triggers:
      - type: GitHub
        github:
          secretReference:
            name: ${APP_NAME}
      - type: ConfigChange
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
            - react-app
          from:
            kind: ImageStreamTag
            name: ${APP_NAME}:latest
- kind: Service
  apiVersion: v1
  metadata:
    labels:
      app: ${APP_NAME}
      app.kubernetes.io/component: react-app
      app.kubernetes.io/instance: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deploymentconfig: ${APP_NAME}
    type: ClusterIP
- kind: ImageStream
  apiVersion: image.openshift.io/v1  
  metadata:
    labels:
      app: ${APP_NAME}
      app.kubernetes.io/component: react-app
      app.kubernetes.io/instance: ${APP_NAME}
    name: nginx
  spec:
    lookupPolicy:
      local: false
    tags:
    - name: latest
      from:
        kind: DockerImage
        name: bitnami/nginx:latest
      annotations:
        openshift.io/imported-from: bitnami/nginx:latest
      referencePolicy:
        type: Source
- kind: ImageStream
  apiVersion: image.openshift.io/v1  
  metadata:
    labels:
      app: ${APP_NAME}
      app.kubernetes.io/component: react-app
      app.kubernetes.io/instance: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    lookupPolicy:
      local: false
- kind: Route
  apiVersion: route.openshift.io/v1  
  metadata:
    labels:
      app: ${APP_NAME}
      app.kubernetes.io/component: react-app
      app.kubernetes.io/instance: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    port:
      targetPort: 8080-tcp      
    to:
      kind: Service
      name: ${APP_NAME}
      weight: 100
    wildcardPolicy: None
    tls:
      termination: Edge
      insecureEdgeTerminationPolicy: None   
- kind: Secret
  apiVersion: v1
  metadata:
    name: ${APP_NAME}
    labels:
      name: ${APP_NAME}
    annotations:
      template.openshift.io/expose-REACT_APP_ISSUER_API_BASE_URL: "{.data['REACT_APP_ISSUER_API_BASE_URL']}"
      template.openshift.io/expose-REACT_APP_OID4VCI_SUPPORTED_CREDENTIAL_ID: "{.data['REACT_APP_OID4VCI_SUPPORTED_CREDENTIAL_ID']}"
      template.openshift.io/expose-webhook-url: "{.data['webhook-url']}"
  stringData:
    REACT_APP_ISSUER_API_BASE_URL: "${REACT_APP_ISSUER_API_BASE_URL}"
    REACT_APP_OID4VCI_SUPPORTED_CREDENTIAL_ID: "${REACT_APP_OID4VCI_SUPPORTED_CREDENTIAL_ID}"
    webhook-url: "${WEBHOOK_URL}"
  type: Opaque
######################################################################
# Parameters
######################################################################      
parameters:
- name: APP_NAME
  displayName: Name
  description: The name assigned to all of the frontend objects defined in this template.    
  required: true
  value: "mdl-issuer-fe"
- name: SOURCE_REPOSITORY_URL
  displayName: Git Repository URL
  description: The URL of the repository with your application source code.    
  required: true
  value: "https://github.com/CQEN-QDCE/exp-mdl.git"
- name: SOURCE_REPOSITORY_REF
  displayName: Git Reference  
  description: Set this to a branch name, tag or other ref of your repository if you
    are not using the default branch.  
  value: "feature/issuer-fe"
- name: CONTEXT_DIR
  displayName: Context Directory
  description: Set this to the relative path to your project if it is not in the root
    of your repository.  
  value: "issuer-frontend"
- name: REACT_APP_ISSUER_API_BASE_URL
  displayName: URL for the issuer API
  description: The URL for the issuer API.
  value: https://mdl-issuer-admin.apps.exp.openshift.cqen.ca
- name: REACT_APP_OID4VCI_SUPPORTED_CREDENTIAL_ID
  displayName: OID4VCI supported credential ID
  description: The OID4VCI supported credential ID.
  value: env-value