@startuml aries_cloudagent_python
allow_mixing

title 
    "Endpoints dans l'agent infonuagique Aries"
end title

' Définition DU CONTRÔLEUR
rectangle "Contrôleur" as resp_pki_saaq

' La PKI de l'Autorité Émettrice
rectangle "PKI de l'Autorité Émettrice" as pki  

' L'agent infonuagique Aries
rectangle "aries-cloudagent-python" as acapy {

    ' Définition des endpoints
    rectangle "endpoints" as endpoints #LightCyan{

        ' Définition des endpoints pour générer des clés de signature
        rectangle "/wallet/x509" as wallet_x509 #LightGoldenRodYellow{
            rectangle "keypair" as keypair #LightGreen{
                rectangle "ECDSA-p256" as ECDSAp256
                rectangle "ECDSA-p384" as ECDSAp384
                rectangle "ECDSA-p521" as ECDSAp521
            }
            rectangle "csr" as csr #LightGreen{
                rectangle "CSR racine" as csr_racine
                rectangle "CSR émettrice" as csr_emettrice  
            }
        }

        ' Définition des endpoints lorsque les clés existent déjà
        rectangle "wallet/verification-method" as wallet_verification_method #LightGoldenRodYellow{
            ' On a besoin de la clé privé, la méthode permet d'aller chercher la clé privé dans le wallet de l'ACA-PY.
            rectangle "sign" as sign 
            
            ' On a besoin de la clé publique, elle va être émise avec un certificat, la méthode permet d'aller chercher la clé publique dans le wallet de l'ACA-PY qui se présente dans un certificat (le verkey).
            rectangle "verify" as verify 
        }
        
    }

    ' Définition des liens et rélations  
    csr_racine -up-> pki : "keypair_racine"
    csr_emettrice -up-> pki : "keypair_emettrice"

    ' Définition des actions de l'acteur 
    resp_pki_saaq -down-> keypair : "Générer une paire de clés"
    resp_pki_saaq -down-> csr : "Générer une demande \nde signature de certificat"
    resp_pki_saaq -down-> sign : "Signer un document mDL"
    resp_pki_saaq -down-> verify : "Vérifier la signature\n d'un document mDL"
}

@enduml
