@startuml mDL
allow_mixing
title
    **Architecture de l'émetteur de permis de conduire numérique - mDL Issuer Architecture**
end title

 
'Références graphique
!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v17.0/dist
!define AzurePuml https://raw.githubusercontent.com/plantuml-stdlib/Azure-PlantUML/release/2-1/dist
!define ICONURL https://raw.githubusercontent.com/Roemer/plantuml-office/master/office2014
 
'Composants graphique
!includeurl AzurePuml/AzureCommon.puml
!includeurl AzurePuml/AzureSimplified.puml
!includeurl AWSPuml/AWSCommon.puml
!includeurl AWSPuml/AWSSimplified.puml
!includeurl AWSPuml/General/Users.puml
!includeurl AWSPuml/General/Mobileclient.puml
!includeurl AWSPuml/General/Client.puml
!includeurl ICONURL/Concepts/link.puml
 
'Environnement d'exécution
rectangle "Environnement d'exécution - Execution environment" as envExecution #WhiteSmoke {
 
    rectangle "Émetteur - Issuer" as issuer #LightCyan {
        agent "Controlleur - Controller (Web)" as issuerController #LightBlue
 
        rectangle "ACA-PY (Rest-API)" as issuerACAPY #LightYellow {
            agent "Serveur admin - Admin server" as issuerAdmin
            agent "Anoncred\n Attestation vérifiable -\n Verifiable Credential" as issuerAnoncred #LightBlue                       
            node "OIDC4VCI (Plugin)" as issuerPlugin #HoneyDew {
                agent "Plugin: Routes admin -\n Admin routes" as issuerPluginAdmin
                agent "Plugin: Routes publiques -\n Public routes" as issuerPluginPublic
                agent "Type de l'attestation - Credential type" as issuerCredentialType #LightBlue
                agent "SD-JWT\n Attestation vérifiable -\n Verifiable Credential" as issuerW3CVC #LightBlue
            }
            node "mDoc (Plugin)" as issuerMDoc #AliceBlue {
                agent "Plugin: Routes admin - Admin routes" as issuerPluginMDocAdmin
                agent "mDL (mDoc/CBOR)" as issuerPluginMDoc #LightBlue
            }

        }
    }
 
    rectangle "Réseau de confiance numérique mDL -\n Network of trust mDL" as networkTrusted #Linen {    
        agent "VICAL" as vicalNetwork #LightBlue   
        agent "PKI" as pkiInfrastructure #LightBlue    
        agent "CANdy" as CandyGouvernance #LightBlue
    }
}
 
node "Détenteur - Holder" as Citizen #LightBlue {
'    Mobileclient(cellC, "Mobile citoyen", "appareil citoyen") #LightBlue
'    Users(UserC, "Citoyens", "Citoyens SAAQ")
'    Users(EmployeSAAQ, "Controlleurs", "Employés SAAQ")
}
 
'DÉFINITION DES LIENS
issuerController <-right-> issuerPluginAdmin #green;line.dashed;
issuerController <-right-> issuerPluginMDocAdmin #green;line.dashed;
issuerAdmin <-up-> networkTrusted #Purple;line.dashed;text:Purple
issuerAdmin <-down-> issuerPluginAdmin #Purple;line.dashed;text:Purple : Routes enregistrées - Registered routes
issuerAdmin <-left-> issuerPluginMDocAdmin #Purple;line.dashed;text:Purple : Routes enregistrées - Registered routes
 
issuerPluginPublic <-left-> issuerCredentialType #Black;line.dashed;text:Black : liaison de périphérique - Device binding
issuerPluginAdmin --> issuerCredentialType #Black;line.dashed;text:Black  : Échange de données - Data exchange
issuerCredentialType --> issuerW3CVC #BlueViolet;line.dashed;text:BlueViolet : W3C VC
issuerCredentialType --> issuerAnoncred #BlueViolet;line.dashed;text:BlueViolet : Anoncred VC
issuerCredentialType ---> issuerPluginMDoc #BlueViolet;line.dashed;text:BlueViolet : mDL
 
Citizen <-right-> issuerPluginPublic #Red;line.dashed;text:red : OIDC4VCI Protocol
Citizen --> issuerController #green;line.dashed;text:green : Lancer d'echange -\n Initiates Exchange
issuerController --> Citizen #green;line.dashed;text:green : Offre d'attestation - Credential offer\n (QR code, etc)

legend
    **Dépôts sources d'inspiration**
   |= Source |= URL |
   | Plugin OID4VCI | https://github.com/hyperledger/aries-acapy-plugins/tree/main/oid4vci |
   | Plugin mDoc | https://github.com/IdentityPython/pyMDOC-CBOR |
   | Cadre de gouvernance du réseau CANdy | https://iccs-isac.github.io/Gouvernance-CICAN-ICDTC-Governance/fr/CANdy%20Network/CANdy-Network-Governance-Framework/ |
   | Le communiqué: Colloque des ministres et des sous-ministres fédéraux,\n provinciaux et territoriaux sur la confiance numérique et la cybersécurité | https://scics.ca/fr/product-produit/les-priorites-en-matiere-de-confiance-numerique-et-de-cybersecurite-ont-fait-lobjet-de-discussions-au-colloque-annuel-des-ministres-federal-provinciaux-et-territoriaux/ |
endlegend
 
@enduml