#!/bin/bash

source base.params

echo -e "\033[32m===== Configurations actives pour le script: [${0##*/}] =====\033[0m" bas
echo "Project Home: $PROJECT_HOME"
echo "Project BKP:  $PROJECT_HOME$PROJECT_BKP_HOME"
echo "Project SRC:  $PROJECT_HOME$PROJECT_SRC_HOME"
echo "PKI Home:     $PKI_HOME"

# Create the main PKI directory
mkdir -p $PKI_HOME

# Create CA directories
for ca in root cqen saaq 
do
    mkdir -p $PKI_HOME/ca/$ca/{db,private,certs,newcerts,crl,config,scripts,csr}

    # Set restrictive permissions for private directories
    chmod 700 $PKI_HOME/ca/$ca/private

    touch $PKI_HOME/ca/$ca/db/index.txt
    echo 1000 > $PKI_HOME/ca/$ca/db/serial
    echo 1000 > $PKI_HOME/ca/$ca/db/crlnumber
    # Create the password files with random strings generated by openssl
    echo $(openssl rand -base64 64) > $PKI_HOME/ca/$ca/private/ca_password.txt

done

# Create the OCSP password file
echo $(openssl rand -base64 64) > $PKI_HOME/ca/cqen/private/ocsp_password.txt

# Create other directories
mkdir -p $PKI_HOME/{cacerts,csr,issued,revoked,scripts,ocsp,db}

# Set appropriate permissions
chmod 755 $PKI_HOME
chmod 755 $PKI_HOME/ca
chmod 755 $PKI_HOME/ca/*
chmod 755 $PKI_HOME/csr
chmod 755 $PKI_HOME/issued
chmod 755 $PKI_HOME/revoked
chmod 755 $PKI_HOME/scripts
chmod 755 $PKI_HOME/ocsp
chmod 755 $PKI_HOME/db
chmod 600 $PKI_HOME/ca/*/private/ca_password.txt
chmod 600 $PKI_HOME/ca/cqen/private/ocsp_password.txt

# Copier les fichiers shell et params vers le repertoire scripts
cp *.sh $PKI_HOME/scripts
cp *.params $PKI_HOME/scripts

echo -e "\033[32m PKI directory structure created successfully at $PKI_HOME\033[0m"

#EOF
