#!/bin/bash

# Define the root directory for the PKI
HOME="</home/dir/a/la/racine/du/projet>"
PKI_ROOT="$HOME/icpGouvQC"

# Create the main PKI directory
mkdir -p $PKI_ROOT

# Create CA directories
for ca in root cqen saaq 
do
    mkdir -p $PKI_ROOT/ca/$ca/{db,private,certs,newcerts,crl,config,scripts,csr}

    # Set restrictive permissions for private directories
    chmod 700 $PKI_ROOT/ca/$ca/private

    touch $PKI_ROOT/ca/$ca/db/index.txt
    echo 1000 > $PKI_ROOT/ca/$ca/db/serial
    echo 1000 > $PKI_ROOT/ca/$ca/db/crlnumber
    # Create the password files with random strings generated by openssl
    echo $(openssl rand -base64 64) > $PKI_ROOT/ca/$ca/private/ca_password.txt


done

# Create the OCSP password file
echo $(openssl rand -base64 64) > $PKI_ROOT/ca/cqen/private/ocsp_password.txt

# Create other directories
mkdir -p $PKI_ROOT/{cacerts,csr,issued,revoked,scripts,ocsp,db}

# Set appropriate permissions
chmod 755 $PKI_ROOT
chmod 755 $PKI_ROOT/ca
chmod 755 $PKI_ROOT/ca/*
chmod 755 $PKI_ROOT/csr
chmod 755 $PKI_ROOT/issued
chmod 755 $PKI_ROOT/revoked
chmod 755 $PKI_ROOT/scripts
chmod 755 $PKI_ROOT/ocsp
chmod 755 $PKI_ROOT/db
chmod 600 $PKI_ROOT/ca/*/private/ca_password.txt
chmod 600 $PKI_ROOT/ca/cqen/private/ocsp_password.txt

echo -e "\033[31m PKI directory structure created successfully at $PKI_ROOT\033[0m"

#EOF
