export enum MobileDrivingLicenceDataElements {
    FAMILY_NAME = "family_name",
    GIVEN_NAME = "given_name",
    BIRTH_DATE = "birth_date",
    ISSUE_DATE = "issue_date",
    EXPIRY_DATE = "expiry_date",
    ISSUING_COUNTRY = "issuing_country",
    ISSUING_AUTHORITY = "issuing_authority",
    DOCUMENT_NUMBER = "document_number",
    PORTRAIT = "portrait",
    DRIVING_PRIVILEGES = "driving_privileges",
    UN_DISTINGUISHING_SIGN = "un_distinguishing_sign",
    ADMINISTRATIVE_NUMBER = "administrative_number",
    SEX = "sex",
    HEIGHT = "height",
    WEIGHT = "weight",
    EYE_COLOUR = "eye_colour",
    HAIR_COLOUR = "hair_colour",
    BIRTH_PLACE = "birth_place",
    RESIDENT_ADDRESS = "resident_address",
    PORTRAIT_CAPTURE_DATE = "portrait_capture_date",
    AGE_IN_YEARS = "age_in_years",
    AGE_BIRTH_YEAR = "age_birth_year",
    AGE_OVER_18 = "age_over_18",
    ISSUING_JURISDICTION = "issuing_jurisdiction",
    NATIONALITY = "nationality",
    RESIDENT_CITY = "resident_city",
    RESIDENT_STATE = "resident_state",
    RESIDENT_POSTAL_CODE = "resident_postal_code",
    RESIDENT_COUNTRY = "resident_country",
    FAMILY_NAME_NATIONAL_CHARACTER = "family_name_national_character",
    GIVEN_NAME_NATIONAL_CHARACTER = "given_name_national_character",
    SIGNATURE_USUAL_MARK = "signature_usual_mark",
}

export class MobileDrivingLicenceAllDataElement {
    public static ALL: MobileDrivingLicenceDataElements[] = [
        MobileDrivingLicenceDataElements.FAMILY_NAME,
        MobileDrivingLicenceDataElements.GIVEN_NAME,
        MobileDrivingLicenceDataElements.BIRTH_DATE,
        MobileDrivingLicenceDataElements.ISSUE_DATE,
        MobileDrivingLicenceDataElements.EXPIRY_DATE,
        MobileDrivingLicenceDataElements.ISSUING_COUNTRY,
        MobileDrivingLicenceDataElements.ISSUING_AUTHORITY,
        MobileDrivingLicenceDataElements.DOCUMENT_NUMBER,
        MobileDrivingLicenceDataElements.PORTRAIT,
        MobileDrivingLicenceDataElements.DRIVING_PRIVILEGES,
        MobileDrivingLicenceDataElements.UN_DISTINGUISHING_SIGN,
        MobileDrivingLicenceDataElements.ADMINISTRATIVE_NUMBER,
        MobileDrivingLicenceDataElements.SEX,
        MobileDrivingLicenceDataElements.HEIGHT,
        MobileDrivingLicenceDataElements.WEIGHT,
        MobileDrivingLicenceDataElements.EYE_COLOUR,
        MobileDrivingLicenceDataElements.HAIR_COLOUR,
        MobileDrivingLicenceDataElements.BIRTH_PLACE,
        MobileDrivingLicenceDataElements.RESIDENT_ADDRESS,
        MobileDrivingLicenceDataElements.PORTRAIT_CAPTURE_DATE,
        MobileDrivingLicenceDataElements.AGE_IN_YEARS,
        MobileDrivingLicenceDataElements.AGE_BIRTH_YEAR,
        MobileDrivingLicenceDataElements.AGE_OVER_18,
        MobileDrivingLicenceDataElements.ISSUING_JURISDICTION,
        MobileDrivingLicenceDataElements.NATIONALITY,
        MobileDrivingLicenceDataElements.RESIDENT_CITY,
        MobileDrivingLicenceDataElements.RESIDENT_STATE,
        MobileDrivingLicenceDataElements.RESIDENT_POSTAL_CODE,
        MobileDrivingLicenceDataElements.RESIDENT_COUNTRY,
        MobileDrivingLicenceDataElements.FAMILY_NAME_NATIONAL_CHARACTER,
        MobileDrivingLicenceDataElements.GIVEN_NAME_NATIONAL_CHARACTER,
        MobileDrivingLicenceDataElements.SIGNATURE_USUAL_MARK,
    ];
}